### ISSUE TITLE
functions have to be at "data" folder to be included in pkg

### ISSUE THREAD

**Issue by imarkonis** [KVHEM/hydrope#1]
Perhaps I am doing something wrong here, but it seems that if the .R file is not in the "hydrope/data" then it is not included in the pkg. In addition, I am not sure if the A.R file should be in both R and data folders.

On the contrary, documentation is produced only for functions in R folder.

**Comment by hanel** [comment]
for sure, the standard location for the R scripts is the hydrope/R folder. There is some mess because of the paths needed for data. I will try to find some clean and clever solution :)

**Comment by hanel** [comment]
I corrected the structure, the trick is to include data/datalist file and set lazyeval = FALSE in description. Now it should work.

Can you check this?
